### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by hrsetyono** [hrsetyono/woocommerce-indo-shipping#2]
- [x] Cache City and Subdistrict AJAX calls
- [ ] Auto detect City based on Postal code 
- [ ] City dropdown not showing when set to allow only single country
